// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: api/source/v1/source.proto

package sourcev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SourceType int32

const (
	SourceType_SOURCE_TYPE_UNSPECIFIED      SourceType = 0
	SourceType_SOURCE_TYPE_TELEGRAM_CHANNEL SourceType = 1
	SourceType_SOURCE_TYPE_TELEGRAM_GROUP   SourceType = 2
	SourceType_SOURCE_TYPE_RSS              SourceType = 3
	SourceType_SOURCE_TYPE_WEB_SCRAPING     SourceType = 4
)

// Enum value maps for SourceType.
var (
	SourceType_name = map[int32]string{
		0: "SOURCE_TYPE_UNSPECIFIED",
		1: "SOURCE_TYPE_TELEGRAM_CHANNEL",
		2: "SOURCE_TYPE_TELEGRAM_GROUP",
		3: "SOURCE_TYPE_RSS",
		4: "SOURCE_TYPE_WEB_SCRAPING",
	}
	SourceType_value = map[string]int32{
		"SOURCE_TYPE_UNSPECIFIED":      0,
		"SOURCE_TYPE_TELEGRAM_CHANNEL": 1,
		"SOURCE_TYPE_TELEGRAM_GROUP":   2,
		"SOURCE_TYPE_RSS":              3,
		"SOURCE_TYPE_WEB_SCRAPING":     4,
	}
)

func (x SourceType) Enum() *SourceType {
	p := new(SourceType)
	*p = x
	return p
}

func (x SourceType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SourceType) Descriptor() protoreflect.EnumDescriptor {
	return file_api_source_v1_source_proto_enumTypes[0].Descriptor()
}

func (SourceType) Type() protoreflect.EnumType {
	return &file_api_source_v1_source_proto_enumTypes[0]
}

func (x SourceType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SourceType.Descriptor instead.
func (SourceType) EnumDescriptor() ([]byte, []int) {
	return file_api_source_v1_source_proto_rawDescGZIP(), []int{0}
}

type TelegramChannelConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChannelId     string                 `protobuf:"bytes,1,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TelegramChannelConfig) Reset() {
	*x = TelegramChannelConfig{}
	mi := &file_api_source_v1_source_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TelegramChannelConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TelegramChannelConfig) ProtoMessage() {}

func (x *TelegramChannelConfig) ProtoReflect() protoreflect.Message {
	mi := &file_api_source_v1_source_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TelegramChannelConfig.ProtoReflect.Descriptor instead.
func (*TelegramChannelConfig) Descriptor() ([]byte, []int) {
	return file_api_source_v1_source_proto_rawDescGZIP(), []int{0}
}

func (x *TelegramChannelConfig) GetChannelId() string {
	if x != nil {
		return x.ChannelId
	}
	return ""
}

type TelegramGroupConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       string                 `protobuf:"bytes,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TelegramGroupConfig) Reset() {
	*x = TelegramGroupConfig{}
	mi := &file_api_source_v1_source_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TelegramGroupConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TelegramGroupConfig) ProtoMessage() {}

func (x *TelegramGroupConfig) ProtoReflect() protoreflect.Message {
	mi := &file_api_source_v1_source_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TelegramGroupConfig.ProtoReflect.Descriptor instead.
func (*TelegramGroupConfig) Descriptor() ([]byte, []int) {
	return file_api_source_v1_source_proto_rawDescGZIP(), []int{1}
}

func (x *TelegramGroupConfig) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

type RssConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FeedUrl       string                 `protobuf:"bytes,1,opt,name=feed_url,json=feedUrl,proto3" json:"feed_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RssConfig) Reset() {
	*x = RssConfig{}
	mi := &file_api_source_v1_source_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RssConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RssConfig) ProtoMessage() {}

func (x *RssConfig) ProtoReflect() protoreflect.Message {
	mi := &file_api_source_v1_source_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RssConfig.ProtoReflect.Descriptor instead.
func (*RssConfig) Descriptor() ([]byte, []int) {
	return file_api_source_v1_source_proto_rawDescGZIP(), []int{2}
}

func (x *RssConfig) GetFeedUrl() string {
	if x != nil {
		return x.FeedUrl
	}
	return ""
}

type WebScrapingConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Selector      string                 `protobuf:"bytes,1,opt,name=selector,proto3" json:"selector,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WebScrapingConfig) Reset() {
	*x = WebScrapingConfig{}
	mi := &file_api_source_v1_source_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WebScrapingConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebScrapingConfig) ProtoMessage() {}

func (x *WebScrapingConfig) ProtoReflect() protoreflect.Message {
	mi := &file_api_source_v1_source_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebScrapingConfig.ProtoReflect.Descriptor instead.
func (*WebScrapingConfig) Descriptor() ([]byte, []int) {
	return file_api_source_v1_source_proto_rawDescGZIP(), []int{3}
}

func (x *WebScrapingConfig) GetSelector() string {
	if x != nil {
		return x.Selector
	}
	return ""
}

type SourceConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Config:
	//
	//	*SourceConfig_TelegramChannel
	//	*SourceConfig_TelegramGroup
	//	*SourceConfig_Rss
	//	*SourceConfig_WebScraping
	Config        isSourceConfig_Config `protobuf_oneof:"config"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SourceConfig) Reset() {
	*x = SourceConfig{}
	mi := &file_api_source_v1_source_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SourceConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SourceConfig) ProtoMessage() {}

func (x *SourceConfig) ProtoReflect() protoreflect.Message {
	mi := &file_api_source_v1_source_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SourceConfig.ProtoReflect.Descriptor instead.
func (*SourceConfig) Descriptor() ([]byte, []int) {
	return file_api_source_v1_source_proto_rawDescGZIP(), []int{4}
}

func (x *SourceConfig) GetConfig() isSourceConfig_Config {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *SourceConfig) GetTelegramChannel() *TelegramChannelConfig {
	if x != nil {
		if x, ok := x.Config.(*SourceConfig_TelegramChannel); ok {
			return x.TelegramChannel
		}
	}
	return nil
}

func (x *SourceConfig) GetTelegramGroup() *TelegramGroupConfig {
	if x != nil {
		if x, ok := x.Config.(*SourceConfig_TelegramGroup); ok {
			return x.TelegramGroup
		}
	}
	return nil
}

func (x *SourceConfig) GetRss() *RssConfig {
	if x != nil {
		if x, ok := x.Config.(*SourceConfig_Rss); ok {
			return x.Rss
		}
	}
	return nil
}

func (x *SourceConfig) GetWebScraping() *WebScrapingConfig {
	if x != nil {
		if x, ok := x.Config.(*SourceConfig_WebScraping); ok {
			return x.WebScraping
		}
	}
	return nil
}

type isSourceConfig_Config interface {
	isSourceConfig_Config()
}

type SourceConfig_TelegramChannel struct {
	TelegramChannel *TelegramChannelConfig `protobuf:"bytes,1,opt,name=telegram_channel,json=telegramChannel,proto3,oneof"`
}

type SourceConfig_TelegramGroup struct {
	TelegramGroup *TelegramGroupConfig `protobuf:"bytes,2,opt,name=telegram_group,json=telegramGroup,proto3,oneof"`
}

type SourceConfig_Rss struct {
	Rss *RssConfig `protobuf:"bytes,3,opt,name=rss,proto3,oneof"`
}

type SourceConfig_WebScraping struct {
	WebScraping *WebScrapingConfig `protobuf:"bytes,4,opt,name=web_scraping,json=webScraping,proto3,oneof"`
}

func (*SourceConfig_TelegramChannel) isSourceConfig_Config() {}

func (*SourceConfig_TelegramGroup) isSourceConfig_Config() {}

func (*SourceConfig_Rss) isSourceConfig_Config() {}

func (*SourceConfig_WebScraping) isSourceConfig_Config() {}

type Source struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          SourceType             `protobuf:"varint,2,opt,name=type,proto3,enum=source.v1.SourceType" json:"type,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Url           string                 `protobuf:"bytes,4,opt,name=url,proto3" json:"url,omitempty"`
	Config        *SourceConfig          `protobuf:"bytes,5,opt,name=config,proto3" json:"config,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Source) Reset() {
	*x = Source{}
	mi := &file_api_source_v1_source_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Source) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Source) ProtoMessage() {}

func (x *Source) ProtoReflect() protoreflect.Message {
	mi := &file_api_source_v1_source_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Source.ProtoReflect.Descriptor instead.
func (*Source) Descriptor() ([]byte, []int) {
	return file_api_source_v1_source_proto_rawDescGZIP(), []int{5}
}

func (x *Source) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Source) GetType() SourceType {
	if x != nil {
		return x.Type
	}
	return SourceType_SOURCE_TYPE_UNSPECIFIED
}

func (x *Source) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Source) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *Source) GetConfig() *SourceConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *Source) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Source) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type CreateSourceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          SourceType             `protobuf:"varint,1,opt,name=type,proto3,enum=source.v1.SourceType" json:"type,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Url           string                 `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`
	Config        *SourceConfig          `protobuf:"bytes,4,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSourceRequest) Reset() {
	*x = CreateSourceRequest{}
	mi := &file_api_source_v1_source_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSourceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSourceRequest) ProtoMessage() {}

func (x *CreateSourceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_source_v1_source_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSourceRequest.ProtoReflect.Descriptor instead.
func (*CreateSourceRequest) Descriptor() ([]byte, []int) {
	return file_api_source_v1_source_proto_rawDescGZIP(), []int{6}
}

func (x *CreateSourceRequest) GetType() SourceType {
	if x != nil {
		return x.Type
	}
	return SourceType_SOURCE_TYPE_UNSPECIFIED
}

func (x *CreateSourceRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateSourceRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *CreateSourceRequest) GetConfig() *SourceConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

type CreateSourceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Source        *Source                `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSourceResponse) Reset() {
	*x = CreateSourceResponse{}
	mi := &file_api_source_v1_source_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSourceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSourceResponse) ProtoMessage() {}

func (x *CreateSourceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_source_v1_source_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSourceResponse.ProtoReflect.Descriptor instead.
func (*CreateSourceResponse) Descriptor() ([]byte, []int) {
	return file_api_source_v1_source_proto_rawDescGZIP(), []int{7}
}

func (x *CreateSourceResponse) GetSource() *Source {
	if x != nil {
		return x.Source
	}
	return nil
}

type GetSourceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSourceRequest) Reset() {
	*x = GetSourceRequest{}
	mi := &file_api_source_v1_source_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSourceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSourceRequest) ProtoMessage() {}

func (x *GetSourceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_source_v1_source_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSourceRequest.ProtoReflect.Descriptor instead.
func (*GetSourceRequest) Descriptor() ([]byte, []int) {
	return file_api_source_v1_source_proto_rawDescGZIP(), []int{8}
}

func (x *GetSourceRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetSourceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Source        *Source                `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSourceResponse) Reset() {
	*x = GetSourceResponse{}
	mi := &file_api_source_v1_source_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSourceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSourceResponse) ProtoMessage() {}

func (x *GetSourceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_source_v1_source_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSourceResponse.ProtoReflect.Descriptor instead.
func (*GetSourceResponse) Descriptor() ([]byte, []int) {
	return file_api_source_v1_source_proto_rawDescGZIP(), []int{9}
}

func (x *GetSourceResponse) GetSource() *Source {
	if x != nil {
		return x.Source
	}
	return nil
}

type UpdateSourceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          SourceType             `protobuf:"varint,2,opt,name=type,proto3,enum=source.v1.SourceType" json:"type,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Url           string                 `protobuf:"bytes,4,opt,name=url,proto3" json:"url,omitempty"`
	Config        *SourceConfig          `protobuf:"bytes,5,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateSourceRequest) Reset() {
	*x = UpdateSourceRequest{}
	mi := &file_api_source_v1_source_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSourceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSourceRequest) ProtoMessage() {}

func (x *UpdateSourceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_source_v1_source_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSourceRequest.ProtoReflect.Descriptor instead.
func (*UpdateSourceRequest) Descriptor() ([]byte, []int) {
	return file_api_source_v1_source_proto_rawDescGZIP(), []int{10}
}

func (x *UpdateSourceRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateSourceRequest) GetType() SourceType {
	if x != nil {
		return x.Type
	}
	return SourceType_SOURCE_TYPE_UNSPECIFIED
}

func (x *UpdateSourceRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateSourceRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *UpdateSourceRequest) GetConfig() *SourceConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

type UpdateSourceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Source        *Source                `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateSourceResponse) Reset() {
	*x = UpdateSourceResponse{}
	mi := &file_api_source_v1_source_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSourceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSourceResponse) ProtoMessage() {}

func (x *UpdateSourceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_source_v1_source_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSourceResponse.ProtoReflect.Descriptor instead.
func (*UpdateSourceResponse) Descriptor() ([]byte, []int) {
	return file_api_source_v1_source_proto_rawDescGZIP(), []int{11}
}

func (x *UpdateSourceResponse) GetSource() *Source {
	if x != nil {
		return x.Source
	}
	return nil
}

type DeleteSourceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSourceRequest) Reset() {
	*x = DeleteSourceRequest{}
	mi := &file_api_source_v1_source_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSourceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSourceRequest) ProtoMessage() {}

func (x *DeleteSourceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_source_v1_source_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSourceRequest.ProtoReflect.Descriptor instead.
func (*DeleteSourceRequest) Descriptor() ([]byte, []int) {
	return file_api_source_v1_source_proto_rawDescGZIP(), []int{12}
}

func (x *DeleteSourceRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteSourceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSourceResponse) Reset() {
	*x = DeleteSourceResponse{}
	mi := &file_api_source_v1_source_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSourceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSourceResponse) ProtoMessage() {}

func (x *DeleteSourceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_source_v1_source_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSourceResponse.ProtoReflect.Descriptor instead.
func (*DeleteSourceResponse) Descriptor() ([]byte, []int) {
	return file_api_source_v1_source_proto_rawDescGZIP(), []int{13}
}

type ListSourcesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PageSize      int32                  `protobuf:"varint,1,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	TypeFilter    SourceType             `protobuf:"varint,3,opt,name=type_filter,json=typeFilter,proto3,enum=source.v1.SourceType" json:"type_filter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSourcesRequest) Reset() {
	*x = ListSourcesRequest{}
	mi := &file_api_source_v1_source_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSourcesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSourcesRequest) ProtoMessage() {}

func (x *ListSourcesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_source_v1_source_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSourcesRequest.ProtoReflect.Descriptor instead.
func (*ListSourcesRequest) Descriptor() ([]byte, []int) {
	return file_api_source_v1_source_proto_rawDescGZIP(), []int{14}
}

func (x *ListSourcesRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListSourcesRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListSourcesRequest) GetTypeFilter() SourceType {
	if x != nil {
		return x.TypeFilter
	}
	return SourceType_SOURCE_TYPE_UNSPECIFIED
}

type ListSourcesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sources       []*Source              `protobuf:"bytes,1,rep,name=sources,proto3" json:"sources,omitempty"`
	TotalCount    int32                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSourcesResponse) Reset() {
	*x = ListSourcesResponse{}
	mi := &file_api_source_v1_source_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSourcesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSourcesResponse) ProtoMessage() {}

func (x *ListSourcesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_source_v1_source_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSourcesResponse.ProtoReflect.Descriptor instead.
func (*ListSourcesResponse) Descriptor() ([]byte, []int) {
	return file_api_source_v1_source_proto_rawDescGZIP(), []int{15}
}

func (x *ListSourcesResponse) GetSources() []*Source {
	if x != nil {
		return x.Sources
	}
	return nil
}

func (x *ListSourcesResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

var File_api_source_v1_source_proto protoreflect.FileDescriptor

const file_api_source_v1_source_proto_rawDesc = "" +
	"\n" +
	"\x1aapi/source/v1/source.proto\x12\tsource.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"6\n" +
	"\x15TelegramChannelConfig\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x01 \x01(\tR\tchannelId\"0\n" +
	"\x13TelegramGroupConfig\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\tR\agroupId\"&\n" +
	"\tRssConfig\x12\x19\n" +
	"\bfeed_url\x18\x01 \x01(\tR\afeedUrl\"/\n" +
	"\x11WebScrapingConfig\x12\x1a\n" +
	"\bselector\x18\x01 \x01(\tR\bselector\"\x9d\x02\n" +
	"\fSourceConfig\x12M\n" +
	"\x10telegram_channel\x18\x01 \x01(\v2 .source.v1.TelegramChannelConfigH\x00R\x0ftelegramChannel\x12G\n" +
	"\x0etelegram_group\x18\x02 \x01(\v2\x1e.source.v1.TelegramGroupConfigH\x00R\rtelegramGroup\x12(\n" +
	"\x03rss\x18\x03 \x01(\v2\x14.source.v1.RssConfigH\x00R\x03rss\x12A\n" +
	"\fweb_scraping\x18\x04 \x01(\v2\x1c.source.v1.WebScrapingConfigH\x00R\vwebScrapingB\b\n" +
	"\x06config\"\x90\x02\n" +
	"\x06Source\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12)\n" +
	"\x04type\x18\x02 \x01(\x0e2\x15.source.v1.SourceTypeR\x04type\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x10\n" +
	"\x03url\x18\x04 \x01(\tR\x03url\x12/\n" +
	"\x06config\x18\x05 \x01(\v2\x17.source.v1.SourceConfigR\x06config\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\x97\x01\n" +
	"\x13CreateSourceRequest\x12)\n" +
	"\x04type\x18\x01 \x01(\x0e2\x15.source.v1.SourceTypeR\x04type\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x10\n" +
	"\x03url\x18\x03 \x01(\tR\x03url\x12/\n" +
	"\x06config\x18\x04 \x01(\v2\x17.source.v1.SourceConfigR\x06config\"A\n" +
	"\x14CreateSourceResponse\x12)\n" +
	"\x06source\x18\x01 \x01(\v2\x11.source.v1.SourceR\x06source\"\"\n" +
	"\x10GetSourceRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\">\n" +
	"\x11GetSourceResponse\x12)\n" +
	"\x06source\x18\x01 \x01(\v2\x11.source.v1.SourceR\x06source\"\xa7\x01\n" +
	"\x13UpdateSourceRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12)\n" +
	"\x04type\x18\x02 \x01(\x0e2\x15.source.v1.SourceTypeR\x04type\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x10\n" +
	"\x03url\x18\x04 \x01(\tR\x03url\x12/\n" +
	"\x06config\x18\x05 \x01(\v2\x17.source.v1.SourceConfigR\x06config\"A\n" +
	"\x14UpdateSourceResponse\x12)\n" +
	"\x06source\x18\x01 \x01(\v2\x11.source.v1.SourceR\x06source\"%\n" +
	"\x13DeleteSourceRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x16\n" +
	"\x14DeleteSourceResponse\"}\n" +
	"\x12ListSourcesRequest\x12\x1b\n" +
	"\tpage_size\x18\x01 \x01(\x05R\bpageSize\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x126\n" +
	"\vtype_filter\x18\x03 \x01(\x0e2\x15.source.v1.SourceTypeR\n" +
	"typeFilter\"c\n" +
	"\x13ListSourcesResponse\x12+\n" +
	"\asources\x18\x01 \x03(\v2\x11.source.v1.SourceR\asources\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount*\x9e\x01\n" +
	"\n" +
	"SourceType\x12\x1b\n" +
	"\x17SOURCE_TYPE_UNSPECIFIED\x10\x00\x12 \n" +
	"\x1cSOURCE_TYPE_TELEGRAM_CHANNEL\x10\x01\x12\x1e\n" +
	"\x1aSOURCE_TYPE_TELEGRAM_GROUP\x10\x02\x12\x13\n" +
	"\x0fSOURCE_TYPE_RSS\x10\x03\x12\x1c\n" +
	"\x18SOURCE_TYPE_WEB_SCRAPING\x10\x042\x98\x03\n" +
	"\rSourceService\x12O\n" +
	"\fCreateSource\x12\x1e.source.v1.CreateSourceRequest\x1a\x1f.source.v1.CreateSourceResponse\x12F\n" +
	"\tGetSource\x12\x1b.source.v1.GetSourceRequest\x1a\x1c.source.v1.GetSourceResponse\x12O\n" +
	"\fUpdateSource\x12\x1e.source.v1.UpdateSourceRequest\x1a\x1f.source.v1.UpdateSourceResponse\x12O\n" +
	"\fDeleteSource\x12\x1e.source.v1.DeleteSourceRequest\x1a\x1f.source.v1.DeleteSourceResponse\x12L\n" +
	"\vListSources\x12\x1d.source.v1.ListSourcesRequest\x1a\x1e.source.v1.ListSourcesResponseB Z\x1efeedium/api/source/v1;sourcev1b\x06proto3"

var (
	file_api_source_v1_source_proto_rawDescOnce sync.Once
	file_api_source_v1_source_proto_rawDescData []byte
)

func file_api_source_v1_source_proto_rawDescGZIP() []byte {
	file_api_source_v1_source_proto_rawDescOnce.Do(func() {
		file_api_source_v1_source_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_source_v1_source_proto_rawDesc), len(file_api_source_v1_source_proto_rawDesc)))
	})
	return file_api_source_v1_source_proto_rawDescData
}

var file_api_source_v1_source_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_source_v1_source_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_api_source_v1_source_proto_goTypes = []any{
	(SourceType)(0),               // 0: source.v1.SourceType
	(*TelegramChannelConfig)(nil), // 1: source.v1.TelegramChannelConfig
	(*TelegramGroupConfig)(nil),   // 2: source.v1.TelegramGroupConfig
	(*RssConfig)(nil),             // 3: source.v1.RssConfig
	(*WebScrapingConfig)(nil),     // 4: source.v1.WebScrapingConfig
	(*SourceConfig)(nil),          // 5: source.v1.SourceConfig
	(*Source)(nil),                // 6: source.v1.Source
	(*CreateSourceRequest)(nil),   // 7: source.v1.CreateSourceRequest
	(*CreateSourceResponse)(nil),  // 8: source.v1.CreateSourceResponse
	(*GetSourceRequest)(nil),      // 9: source.v1.GetSourceRequest
	(*GetSourceResponse)(nil),     // 10: source.v1.GetSourceResponse
	(*UpdateSourceRequest)(nil),   // 11: source.v1.UpdateSourceRequest
	(*UpdateSourceResponse)(nil),  // 12: source.v1.UpdateSourceResponse
	(*DeleteSourceRequest)(nil),   // 13: source.v1.DeleteSourceRequest
	(*DeleteSourceResponse)(nil),  // 14: source.v1.DeleteSourceResponse
	(*ListSourcesRequest)(nil),    // 15: source.v1.ListSourcesRequest
	(*ListSourcesResponse)(nil),   // 16: source.v1.ListSourcesResponse
	(*timestamppb.Timestamp)(nil), // 17: google.protobuf.Timestamp
}
var file_api_source_v1_source_proto_depIdxs = []int32{
	1,  // 0: source.v1.SourceConfig.telegram_channel:type_name -> source.v1.TelegramChannelConfig
	2,  // 1: source.v1.SourceConfig.telegram_group:type_name -> source.v1.TelegramGroupConfig
	3,  // 2: source.v1.SourceConfig.rss:type_name -> source.v1.RssConfig
	4,  // 3: source.v1.SourceConfig.web_scraping:type_name -> source.v1.WebScrapingConfig
	0,  // 4: source.v1.Source.type:type_name -> source.v1.SourceType
	5,  // 5: source.v1.Source.config:type_name -> source.v1.SourceConfig
	17, // 6: source.v1.Source.created_at:type_name -> google.protobuf.Timestamp
	17, // 7: source.v1.Source.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 8: source.v1.CreateSourceRequest.type:type_name -> source.v1.SourceType
	5,  // 9: source.v1.CreateSourceRequest.config:type_name -> source.v1.SourceConfig
	6,  // 10: source.v1.CreateSourceResponse.source:type_name -> source.v1.Source
	6,  // 11: source.v1.GetSourceResponse.source:type_name -> source.v1.Source
	0,  // 12: source.v1.UpdateSourceRequest.type:type_name -> source.v1.SourceType
	5,  // 13: source.v1.UpdateSourceRequest.config:type_name -> source.v1.SourceConfig
	6,  // 14: source.v1.UpdateSourceResponse.source:type_name -> source.v1.Source
	0,  // 15: source.v1.ListSourcesRequest.type_filter:type_name -> source.v1.SourceType
	6,  // 16: source.v1.ListSourcesResponse.sources:type_name -> source.v1.Source
	7,  // 17: source.v1.SourceService.CreateSource:input_type -> source.v1.CreateSourceRequest
	9,  // 18: source.v1.SourceService.GetSource:input_type -> source.v1.GetSourceRequest
	11, // 19: source.v1.SourceService.UpdateSource:input_type -> source.v1.UpdateSourceRequest
	13, // 20: source.v1.SourceService.DeleteSource:input_type -> source.v1.DeleteSourceRequest
	15, // 21: source.v1.SourceService.ListSources:input_type -> source.v1.ListSourcesRequest
	8,  // 22: source.v1.SourceService.CreateSource:output_type -> source.v1.CreateSourceResponse
	10, // 23: source.v1.SourceService.GetSource:output_type -> source.v1.GetSourceResponse
	12, // 24: source.v1.SourceService.UpdateSource:output_type -> source.v1.UpdateSourceResponse
	14, // 25: source.v1.SourceService.DeleteSource:output_type -> source.v1.DeleteSourceResponse
	16, // 26: source.v1.SourceService.ListSources:output_type -> source.v1.ListSourcesResponse
	22, // [22:27] is the sub-list for method output_type
	17, // [17:22] is the sub-list for method input_type
	17, // [17:17] is the sub-list for extension type_name
	17, // [17:17] is the sub-list for extension extendee
	0,  // [0:17] is the sub-list for field type_name
}

func init() { file_api_source_v1_source_proto_init() }
func file_api_source_v1_source_proto_init() {
	if File_api_source_v1_source_proto != nil {
		return
	}
	file_api_source_v1_source_proto_msgTypes[4].OneofWrappers = []any{
		(*SourceConfig_TelegramChannel)(nil),
		(*SourceConfig_TelegramGroup)(nil),
		(*SourceConfig_Rss)(nil),
		(*SourceConfig_WebScraping)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_source_v1_source_proto_rawDesc), len(file_api_source_v1_source_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_source_v1_source_proto_goTypes,
		DependencyIndexes: file_api_source_v1_source_proto_depIdxs,
		EnumInfos:         file_api_source_v1_source_proto_enumTypes,
		MessageInfos:      file_api_source_v1_source_proto_msgTypes,
	}.Build()
	File_api_source_v1_source_proto = out.File
	file_api_source_v1_source_proto_goTypes = nil
	file_api_source_v1_source_proto_depIdxs = nil
}
