// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: api/source/v1/source.proto

package sourcev1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "feedium/api/source/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// SourceServiceName is the fully-qualified name of the SourceService service.
	SourceServiceName = "source.v1.SourceService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// SourceServiceCreateSourceProcedure is the fully-qualified name of the SourceService's
	// CreateSource RPC.
	SourceServiceCreateSourceProcedure = "/source.v1.SourceService/CreateSource"
	// SourceServiceGetSourceProcedure is the fully-qualified name of the SourceService's GetSource RPC.
	SourceServiceGetSourceProcedure = "/source.v1.SourceService/GetSource"
	// SourceServiceUpdateSourceProcedure is the fully-qualified name of the SourceService's
	// UpdateSource RPC.
	SourceServiceUpdateSourceProcedure = "/source.v1.SourceService/UpdateSource"
	// SourceServiceDeleteSourceProcedure is the fully-qualified name of the SourceService's
	// DeleteSource RPC.
	SourceServiceDeleteSourceProcedure = "/source.v1.SourceService/DeleteSource"
	// SourceServiceListSourcesProcedure is the fully-qualified name of the SourceService's ListSources
	// RPC.
	SourceServiceListSourcesProcedure = "/source.v1.SourceService/ListSources"
)

// SourceServiceClient is a client for the source.v1.SourceService service.
type SourceServiceClient interface {
	CreateSource(context.Context, *connect.Request[v1.CreateSourceRequest]) (*connect.Response[v1.CreateSourceResponse], error)
	GetSource(context.Context, *connect.Request[v1.GetSourceRequest]) (*connect.Response[v1.GetSourceResponse], error)
	UpdateSource(context.Context, *connect.Request[v1.UpdateSourceRequest]) (*connect.Response[v1.UpdateSourceResponse], error)
	DeleteSource(context.Context, *connect.Request[v1.DeleteSourceRequest]) (*connect.Response[v1.DeleteSourceResponse], error)
	ListSources(context.Context, *connect.Request[v1.ListSourcesRequest]) (*connect.Response[v1.ListSourcesResponse], error)
}

// NewSourceServiceClient constructs a client for the source.v1.SourceService service. By default,
// it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and
// sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC()
// or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewSourceServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) SourceServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	sourceServiceMethods := v1.File_api_source_v1_source_proto.Services().ByName("SourceService").Methods()
	return &sourceServiceClient{
		createSource: connect.NewClient[v1.CreateSourceRequest, v1.CreateSourceResponse](
			httpClient,
			baseURL+SourceServiceCreateSourceProcedure,
			connect.WithSchema(sourceServiceMethods.ByName("CreateSource")),
			connect.WithClientOptions(opts...),
		),
		getSource: connect.NewClient[v1.GetSourceRequest, v1.GetSourceResponse](
			httpClient,
			baseURL+SourceServiceGetSourceProcedure,
			connect.WithSchema(sourceServiceMethods.ByName("GetSource")),
			connect.WithClientOptions(opts...),
		),
		updateSource: connect.NewClient[v1.UpdateSourceRequest, v1.UpdateSourceResponse](
			httpClient,
			baseURL+SourceServiceUpdateSourceProcedure,
			connect.WithSchema(sourceServiceMethods.ByName("UpdateSource")),
			connect.WithClientOptions(opts...),
		),
		deleteSource: connect.NewClient[v1.DeleteSourceRequest, v1.DeleteSourceResponse](
			httpClient,
			baseURL+SourceServiceDeleteSourceProcedure,
			connect.WithSchema(sourceServiceMethods.ByName("DeleteSource")),
			connect.WithClientOptions(opts...),
		),
		listSources: connect.NewClient[v1.ListSourcesRequest, v1.ListSourcesResponse](
			httpClient,
			baseURL+SourceServiceListSourcesProcedure,
			connect.WithSchema(sourceServiceMethods.ByName("ListSources")),
			connect.WithClientOptions(opts...),
		),
	}
}

// sourceServiceClient implements SourceServiceClient.
type sourceServiceClient struct {
	createSource *connect.Client[v1.CreateSourceRequest, v1.CreateSourceResponse]
	getSource    *connect.Client[v1.GetSourceRequest, v1.GetSourceResponse]
	updateSource *connect.Client[v1.UpdateSourceRequest, v1.UpdateSourceResponse]
	deleteSource *connect.Client[v1.DeleteSourceRequest, v1.DeleteSourceResponse]
	listSources  *connect.Client[v1.ListSourcesRequest, v1.ListSourcesResponse]
}

// CreateSource calls source.v1.SourceService.CreateSource.
func (c *sourceServiceClient) CreateSource(ctx context.Context, req *connect.Request[v1.CreateSourceRequest]) (*connect.Response[v1.CreateSourceResponse], error) {
	return c.createSource.CallUnary(ctx, req)
}

// GetSource calls source.v1.SourceService.GetSource.
func (c *sourceServiceClient) GetSource(ctx context.Context, req *connect.Request[v1.GetSourceRequest]) (*connect.Response[v1.GetSourceResponse], error) {
	return c.getSource.CallUnary(ctx, req)
}

// UpdateSource calls source.v1.SourceService.UpdateSource.
func (c *sourceServiceClient) UpdateSource(ctx context.Context, req *connect.Request[v1.UpdateSourceRequest]) (*connect.Response[v1.UpdateSourceResponse], error) {
	return c.updateSource.CallUnary(ctx, req)
}

// DeleteSource calls source.v1.SourceService.DeleteSource.
func (c *sourceServiceClient) DeleteSource(ctx context.Context, req *connect.Request[v1.DeleteSourceRequest]) (*connect.Response[v1.DeleteSourceResponse], error) {
	return c.deleteSource.CallUnary(ctx, req)
}

// ListSources calls source.v1.SourceService.ListSources.
func (c *sourceServiceClient) ListSources(ctx context.Context, req *connect.Request[v1.ListSourcesRequest]) (*connect.Response[v1.ListSourcesResponse], error) {
	return c.listSources.CallUnary(ctx, req)
}

// SourceServiceHandler is an implementation of the source.v1.SourceService service.
type SourceServiceHandler interface {
	CreateSource(context.Context, *connect.Request[v1.CreateSourceRequest]) (*connect.Response[v1.CreateSourceResponse], error)
	GetSource(context.Context, *connect.Request[v1.GetSourceRequest]) (*connect.Response[v1.GetSourceResponse], error)
	UpdateSource(context.Context, *connect.Request[v1.UpdateSourceRequest]) (*connect.Response[v1.UpdateSourceResponse], error)
	DeleteSource(context.Context, *connect.Request[v1.DeleteSourceRequest]) (*connect.Response[v1.DeleteSourceResponse], error)
	ListSources(context.Context, *connect.Request[v1.ListSourcesRequest]) (*connect.Response[v1.ListSourcesResponse], error)
}

// NewSourceServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewSourceServiceHandler(svc SourceServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	sourceServiceMethods := v1.File_api_source_v1_source_proto.Services().ByName("SourceService").Methods()
	sourceServiceCreateSourceHandler := connect.NewUnaryHandler(
		SourceServiceCreateSourceProcedure,
		svc.CreateSource,
		connect.WithSchema(sourceServiceMethods.ByName("CreateSource")),
		connect.WithHandlerOptions(opts...),
	)
	sourceServiceGetSourceHandler := connect.NewUnaryHandler(
		SourceServiceGetSourceProcedure,
		svc.GetSource,
		connect.WithSchema(sourceServiceMethods.ByName("GetSource")),
		connect.WithHandlerOptions(opts...),
	)
	sourceServiceUpdateSourceHandler := connect.NewUnaryHandler(
		SourceServiceUpdateSourceProcedure,
		svc.UpdateSource,
		connect.WithSchema(sourceServiceMethods.ByName("UpdateSource")),
		connect.WithHandlerOptions(opts...),
	)
	sourceServiceDeleteSourceHandler := connect.NewUnaryHandler(
		SourceServiceDeleteSourceProcedure,
		svc.DeleteSource,
		connect.WithSchema(sourceServiceMethods.ByName("DeleteSource")),
		connect.WithHandlerOptions(opts...),
	)
	sourceServiceListSourcesHandler := connect.NewUnaryHandler(
		SourceServiceListSourcesProcedure,
		svc.ListSources,
		connect.WithSchema(sourceServiceMethods.ByName("ListSources")),
		connect.WithHandlerOptions(opts...),
	)
	return "/source.v1.SourceService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case SourceServiceCreateSourceProcedure:
			sourceServiceCreateSourceHandler.ServeHTTP(w, r)
		case SourceServiceGetSourceProcedure:
			sourceServiceGetSourceHandler.ServeHTTP(w, r)
		case SourceServiceUpdateSourceProcedure:
			sourceServiceUpdateSourceHandler.ServeHTTP(w, r)
		case SourceServiceDeleteSourceProcedure:
			sourceServiceDeleteSourceHandler.ServeHTTP(w, r)
		case SourceServiceListSourcesProcedure:
			sourceServiceListSourcesHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedSourceServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedSourceServiceHandler struct{}

func (UnimplementedSourceServiceHandler) CreateSource(context.Context, *connect.Request[v1.CreateSourceRequest]) (*connect.Response[v1.CreateSourceResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("source.v1.SourceService.CreateSource is not implemented"))
}

func (UnimplementedSourceServiceHandler) GetSource(context.Context, *connect.Request[v1.GetSourceRequest]) (*connect.Response[v1.GetSourceResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("source.v1.SourceService.GetSource is not implemented"))
}

func (UnimplementedSourceServiceHandler) UpdateSource(context.Context, *connect.Request[v1.UpdateSourceRequest]) (*connect.Response[v1.UpdateSourceResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("source.v1.SourceService.UpdateSource is not implemented"))
}

func (UnimplementedSourceServiceHandler) DeleteSource(context.Context, *connect.Request[v1.DeleteSourceRequest]) (*connect.Response[v1.DeleteSourceResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("source.v1.SourceService.DeleteSource is not implemented"))
}

func (UnimplementedSourceServiceHandler) ListSources(context.Context, *connect.Request[v1.ListSourcesRequest]) (*connect.Response[v1.ListSourcesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("source.v1.SourceService.ListSources is not implemented"))
}
